### ISSUE TITLE
Archive projct?

### ISSUE THREAD

**Issue by schirner** [mroftei/TerrainGeneration#1]
It seems that the terrain generation is now part of the [data set repository](https://github.com/mroftei/fed-amr-ds). [ScenarioGenerator.py](https://github.com/mroftei/fed-amr-ds/blob/master/ScenarioGenerator.py)

If we don't need this repo anymore, please archive.

**Comment by SpontaneousDuck** [comment]
Leaving here as separate python module for use in dataset and Model zoo
