### ISSUE TITLE
Optimizer not spraying correctly

### ISSUE THREAD

**Issue by SpontaneousDuck** [mroftei/TerrainGeneration#16]
When the tx location and initial rx location have the same x value, the sprayed tensor has all the same value. Issue appears to be [here](https://github.com/mroftei/TerrainGeneration/blob/618f0ef3e0968b5856b377585b333eda0a4c89ba/scenario_generator/Optimizer.py#L98) where the y value depends on the x value.

Example case:
![image](https://github.com/user-attachments/assets/9f8634f7-f39a-4770-9b25-206f35fc71f8)

**Comment by SpontaneousDuck** [comment]
If there is no difference in the min and max x value (vector is vertical), the sprayed x vector will be constant and cause the y vector to also be constant

**Comment by nishanthmarer** [comment]
The problem occurs when the line is vertical and the slope is infinity.

Issues has been fixed by adding an extra equation which calculates equally spaced y values when the line is vertical
