### ISSUE TITLE
Missing catch for impossible situations before trying

### ISSUE THREAD

**Issue by SpontaneousDuck** [mroftei/TerrainGeneration#17]
If a requested SNR is significantly outside of the possible on the far end, the optimizer will try anyways instead of bouncing out and requesting a scenario regeneration. 

Example:
Estimate minimum power for a channel in `power_est_db` is -141dB but the requested power is -158dB. 

The optimizer will still try and make this when it is clearly impossible and it would just be better to regenerate the scenario.

Moving a receiver closer is always possible but farther is not so this check probably only needs to be on the maximum distance/minimum power possible. Maybe add a parameter for tolerance on the lower end so close values are still possible. (-141 is estimated min but requested is-142 is still possible but -152 is not).

**Comment by nishanthmarer** [comment]
added a new tolerance parameter "lowEnd_Tolerance_dB",
 
to reduce by 2dB then set the value as -2
 
to increase by 2dB, then set the value as 2
